name: bookshelf
description: (Ero)Manga viewer.
version: 2.0.0-dev0

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_statusbarcolor: any
  flutter_bloc: any
  flutter_redux: any
  html: any
  sembast: any
  path_provider: any
  dio: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  redux_remote_devtools: any
  mockito: any

flutter:
  uses-material-design: true
  assets:
    - locale/en_US.json
    - locale/zh_Hans_CN.json
