name: bookshelf
description: A bookshelf app.

dependencies:
  flutter:
    sdk: flutter
  html: any
  shared_preferences: any
  http: any
  sembast: any
  path_provider: any
  intl: any
  battery: any
  quiver: '>=0.26.2 <0.27.0'
  minibus: any
  quick_actions: any
  flutter_advanced_networkimage: '^0.1.1'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
