name: bookshelf
description: A bookshelf app.

dependencies:
  flutter:
    sdk: flutter
  html: any
  shared_preferences: any
  http: any
  sembast: any
  path_provider: any
  intl: any
  battery: any
  quiver: any
  quick_actions: any
  url_launcher: any
  flutter_advanced_networkimage: any
  flutter_keepscreenon: any

dev_dependencies:
 flutter_test:
   sdk: flutter

flutter:
  uses-material-design: true
